Shop/Shop/ViewModels/BooksListViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Shop.ViewModels
{
    public class BooksListViewModel
    {
        public IEnumerable<Book> allBooks { get; set; } 

        public string currCategory { get; set; }
    }

}

Shop/Shop/ViewModels/HomeViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Book> favBooks { get; set; }
    }
}

Shop/Shop/ViewModels/ShopCartViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

Shop/Shop/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;

namespace Shop.Controllers
{
    public class BooksController : Controller
    {
        private readonly IAllBooks _allBooks;
        private readonly IBooksCategory _allCategories;

        public BooksController(IAllBooks iAllBooks, IBooksCategory iBooksCat)
        {
            _allBooks = iAllBooks;
            _allCategories = iBooksCat;
        }

        [Route("Books/List")]
        [Route("Books/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Book> books = null;
            string currCategory = "";
            if(string.IsNullOrEmpty(category))
            {
                books = _allBooks.Books.OrderBy(i => i.id);
            }
            else
            {
                if(string.Equals("soft", category, StringComparison.OrdinalIgnoreCase))
                {
                    books = _allBooks.Books.Where(i => i.Category.categoryName.Equals("М'яка обкладинка")).OrderBy(i => i.id);
                    currCategory = "М'яка обкладинка";
                }
                else if (string.Equals("hard", category, StringComparison.OrdinalIgnoreCase))
                {
                    books = _allBooks.Books.Where(i => i.Category.categoryName.Equals("Тверда обкладинка")).OrderBy(i => i.id);
                    currCategory = "Тверда обкладинка";
                }

                             
            }

            var bookObj = new BooksListViewModel
            {
                allBooks = books,
                currCategory = currCategory
            };          
            

            return View(bookObj);
        }
    }
}

Shop/Shop/Controllers/HomeController.cs
using Shop.Data.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.ViewModels;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllBooks _bookRep;
        

        public HomeController(IAllBooks bookRep)
        {
            _bookRep = bookRep;           
        }

        public ViewResult Index()
        {
            var homeBooks = new HomeViewModel
            {
                favBooks = _bookRep.getFavBooks
            };            

            return View(homeBooks);
        }
    }
}

Shop/Shop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.listShopItems = shopCart.getShopItems();

            if(shopCart.listShopItems.Count == 0)
            {
                ModelState.AddModelError("", "Відсутнє замовлення");
            }

            if(ModelState.IsValid)
            {
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }
            
            return View();
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Замовлення успішно опрацьовано, очікуйте книжки та замовляйте знову";
            
            return View();
        }
    }
}

Shop/Shop/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.Data.Repository;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllBooks _bookRep;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllBooks bookRep, ShopCart shopCart)
        {
            _bookRep = bookRep;
            _shopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };            

            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _bookRep.Books.FirstOrDefault(i => i.id == id);
            if(item!= null)
            {
                _shopCart.AddToCart(item);
            }
            
            return RedirectToAction("Index");
        }

    }
}

Shop/Shop/Views/Books/List.cshtml
<h1>Всі книжки</h1>
<h3>@Model.currCategory</h3>
<div class="row mt-5 mb-3">
    @{
        foreach (Book book in Model.allBooks)
        {
            @Html.Partial("AllBooks", book)   
        }
    }
</div>

Shop/Shop/Views/Home/Index.cshtml
@model HomeViewModel

<h1>Радимо до покупки</h1>
<div class="row mt-5 mb-2" />
    @{
        foreach (Book book in Model.favBooks)
        {
            @Html.Partial("AllBooks", book)
        }
    }
</div>

Shop/Shop/Views/Order/Checkout.cshtml
@model Order

<div class="row-2">
    <p><h3>Оформлення замовлення</h3></p>
    <p>
        <form asp-action="Checkout" method="post" class="form-horisontal">
            <div class="form-group">
                <label asp-for="name"></label>
                <div class="col-md-100">
                    <input asp-for="name" class="form-control" />
                    <span asp-validation-for="name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="surname"></label>
                <div class="col-md-100">
                    <input asp-for="surname" class="form-control" />
                    <span asp-validation-for="surname" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="adress"></label>
                <div class="col-md-100">
                    <input asp-for="adress" class="form-control" />
                    <span asp-validation-for="adress" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="phone"></label>
                <div class="col-md-100">
                    <input asp-for="phone" class="form-control" />
                    <span asp-validation-for="phone" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="email"></label>
                <div class="col-md-100">
                    <input asp-for="email" class="form-control" />
                    <span asp-validation-for="email" class="text-danger"></span>
                </div>
            </div>
            <input class="btn btn-success" type="submit" value="Оформити замовлення" />
        </form>
    </p>
</div>

Shop/Shop/Views/Order/Complete.cshtml
<h1>@ViewBag.Message</h1>

Shop/Shop/Views/Shared/AllBooks.cshtml
@model Book

<div class="col-lg-4">
    <div class="card shadw-sm">
        <img class="card-img-top" width="100%" height="100%" src="@Model.img" alt="@Model.name" />
        <div class="card-body">
            <p class="card-text">@Model.name<br /> @Model.author <br /> @Model.shortDesc</p>
            <div class="d-flex justify-content-between align-items-center">
                <a class="btn btn-warning" asp-controller="ShopCart" asp-action="AddToCart" asp-route-id="@Model.id">Купити</a></p>
                <small class="text-muted"> @Model.price.ToString("c")</small>
            </div>
        </div>        
    </div>
</div>

Shop/Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />    
    <title>BookSomi</title>
    <link rel="icon" href="https://uxwing.com/wp-content/themes/uxwing/download/18-education-school/read-book.png" type="image/x-icon"/>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="py-2 navbar navbar-expand navbar-dark bg-dark ">
            <div class="container-fluid">
                <a class="navbar-brand"><i class="bi bi-book"></i> BookSomi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarsExample02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Головна</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Books/List">Книжки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Books/List/soft">М'яка обкладинка</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Books/List/hard">Тверда обкладинка</a>
                        </li>
                        
                    </ul>
                    <ul class="navbar-nav">                        
                        <li class="nav-item text-nowrap">
                            <a class="nav-link" href="/ShopCart/"><i class="bi bi-bag"></i>Кошик</a>
                        </li>
                    </ul>
</div>
            </div>
        </nav>
    </header>

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="container row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                @RenderBody()
            </div>
        </div>
    </div>
    
    <footer class="container">
        <p class="float-end"><a href="#">Вверх</a></p>
        <p>© BookSomi Shop</p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

Shop/Shop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<div class ="container">
    @foreach(var el in Model.shopCart.listShopItems)
    {
        <div class="alert alert-warning mt-3">
            <b>Книжка:</b> @el.book.name<br />
            <b>Ціна:</b> @el.book.price.ToString("c")
        </div>
    }
    <hr />
    <a class="btn btn-danger mb-10" asp-controller="Order" asp-action="Checkout"><i class="bi bi-wallet"></i> </a>
</div>